version: "1.0.0"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
      - /var/storage:/var/storage
    ports:
      - "5029:5029"
    links:
      - db
  pg_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admonql
      POSTGRES_USER: admin
      POSTGRES_DB: storage
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  migrate:
    profiles: ["tools"]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://admin@db/storage?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - pg_db
    volumes:
      - ./schema:/tmp/migrations
  create-migration:
    <<: *basemigrate
    entrypoint:  migrate create -dir /tmp/migrations -ext sql
    command: ""
volumes:
  data: