version: "3.8"

services:
  db:
    image: postgres
    container_name: "database"
    restart: always
    environment:
      - POSTGRES_PASSWORD=admonql
      - POSTGRES_USER=admin
      - POSTGRES_DB=storage
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - fullnet
  app:
    build: .
    container_name: "storage"
    environment:
      - DB_PASSWORD=admonql
      - STORAGE_DIR=/var/storage
    volumes:
      - .:/opt/app/api
      - /var/storage:/var/storage
    ports:
      - "185.104.114.6:5029:5029"
    depends_on:
      - db
    networks:
      - fullnet
  migrate: &basemigrate
    profiles: ["tools"]
    image: migrate/migrate
    entrypoint: "migrate -database postgres://admin:admonql@db/storage?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./schema:/tmp/migrations
  create-migration:
    <<: *basemigrate
    entrypoint:  migrate create -dir /tmp/migrations -ext sql
    command: ""

volumes:
  data:

networks:
  fullnet:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "false"
