http:
  port: 5029
  readTimeout: 15s
  writeTimeout: 15s
  maxHeaderMegabytes: 10

cache:
  ttl: 30m
  clean: 1h


limiter:
  rps: 10
  burst: 20
  ttl: 10m

database:
  postgres:
    dbName: storage
    port: 5432
    host: localhost
    user: postgres