http:
  port: 5029
  readTimeout: 15s
  writeTimeout: 15s
  maxHeaderMegabytes: 10

cache:
  ttl: 60s

limiter:
  rps: 10
  burst: 20
  ttl: 10m

database:
  postgres:
    dbName: storage
    port: 5432
    host: "185.104.114.6"
    user: admin